first-homework
js-tasks-ru/jsbasic-20220922_elizaveta3 pull request #1
Opened 2022-09-25 22:23 UTC by LisaB1994

2022-09-25 22:23 UTC, jsru commented
Спасибо за отправленный пулриквест, теперь @koalex должен запустить тесты.

2022-09-26 07:28 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-09-26 07:29 UTC, koalex requested changes
Исправить замечания

2022-09-26 07:29 UTC, koalex commented on 0-module/1-task/index.js
> +alert(sum(1, 1));
Удалить `alert`-ы

2022-09-26 07:29 UTC, koalex commented on 0-module/1-task/index.js
> +alert(sum1(2,5));
Удалить `alert`

2022-09-26 07:29 UTC, koalex commented on 0-module/1-task/index.js
> +function sum1(m, n) {
Зачем эта ф-ция? Удалить

2022-09-26 11:31 UTC, LisaB1994 commented on 0-module/1-task/index.js
> +alert(sum(1, 1));
я думала нужно вывести значения сообщением

2022-09-26 11:34 UTC, LisaB1994 commented on 0-module/1-task/index.js
> +function sum1(m, n) {
удалила

2022-09-26 12:05 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2022-09-26 12:05 UTC, koalex approved these changes

2022-09-26 12:05 UTC, merged